name: CanElevation_PointClouds
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - geopandas
  - ipyleaflet
  - matplotlib
  - notebook
  - pdal
  - pip
  - pyproj
  - python-pdal
  - requests
  - rioxarray
