name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material mkdocs-static-i18n nbconvert
        
    - name: Set site URL for fork
      run: |
        # Extract username and repo name from GitHub context
        REPO_OWNER="${{ github.repository_owner }}"
        REPO_NAME="${{ github.event.repository.name }}"
        
        # Update mkdocs.yml with the correct site URL
        sed -i "s|site_url: https://nrcan.github.io/CanElevation/|site_url: https://${REPO_OWNER}.github.io/${REPO_NAME}/|g" mkdocs.yml
        sed -i "s|repo_url: https://github.com/NRCan/CanElevation|repo_url: https://github.com/${REPO_OWNER}/${REPO_NAME}|g" mkdocs.yml
        sed -i "s|repo_name: NRCan/CanElevation|repo_name: ${REPO_OWNER}/${REPO_NAME}|g" mkdocs.yml
        
        echo "Updated mkdocs.yml for repository: ${REPO_OWNER}/${REPO_NAME}"
        
    - name: Make scripts executable
      run: chmod +x scripts/build-docs.sh
      
    - name: Build documentation
      run: |
        ./scripts/build-docs.sh
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4